repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local # to strip ipynb output cells
  hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [pre-commit]
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace